# Generated by Django 5.1 on 2024-09-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlett', '0002_book_author_book_is_bestselling_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
