# Generated by Django 5.1 on 2024-09-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlett', '0006_address_author_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address Entries'},
        ),
    ]
